### ISSUE TITLE
error NOT_FOUND: Object s3://... does not exist

### ISSUE THREAD

**Issue by nadgirsanket** [jeongukjae/tf-serving-s3#1]
Hi @jeongukjae 

Thank you so much for putting in the effort to create a tf-serving image with tf-io.

I was facing the same issue as well. I want to run tf-serving:2.11.0 and use s3 for models but I couldn't do it from the official image.

I tried to use your image. However, instead of the "S3 UNIMPLEMENTED" error, I am getting:
`error NOT_FOUND: Object s3://... does not exist`

I am using minio as s3 and I am passing all the env variables except `AWS_DEFAULT_REGION`

Can you please tell me if you have come across the above error? and also if your image works with minio S3 storage or is it specifically built for AWS?

Thank you so much. Appreciate it.

**Comment by jeongukjae** [comment]
Hi @nadgirsanket.

Since I didn't change the behavior of S3 support of tensorflow-io, you have to pass all the env vars like using TF-IO.

Can you check the S3_ENDPOINT environment variable?

* related issue: https://github.com/tensorflow/io/issues/1549
* related code: https://github.com/tensorflow/io/blob/v0.29.0/tensorflow_io/core/filesystems/s3/s3_filesystem.cc#L189-L190

**Comment by nadgirsanket** [comment]
Hello @jeongukjae 

Thanks for the response and links. I am setting `S3_ENDPOINT` along with other env vars. I will check if anything is missed.
